ifndef::imagesdir[:imagesdir: imgs]
:tip-caption: 💡
:warning-caption: ⚠️
:toclevels: 4

== Development FAQ
:toc:

=== How to override a Sirius Web service

In some cases you will need to override service to provided by Sirius Web.
To do so, create a custom implementation of the service and use the annotation `org.eclipse.papyrus.web.sirius.contributions.ServiceOverride`.
You need to specify the overridden service in the annotation.
This information is only here to keep tracks.
It is important when bumping _sirius component_ version in order to keeps tracks of the changes applied to the overridden services.

=== How to find/use all concepts model

In order to populate UML tab of Details panel with each UML concept content, we created a single model that contains all UML concepts. This model can be uploaded inside Papyrus web (via `Upload Model` from Explorer view). The UML file is located inside the following directory:
```
<papyrus-web repo>/backend/papyrus-web-application/src/test/resources/models/all-concepts/
```
In order to locate each concept inside the model, we defined an index giving the path of each UML concept inside this model. This file, `all-concepts.txt` is located inside the same above directory. For instance, the concept `ComponentRealization` has the following entry in the index:
```
ComponentRealization -> Model::Activity::CollaborationUse::ComponentRealization
```
This indicates that this concept can be found inside `CollaborationUse` which is a child of `Activity`.
